
server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.94.23.76:3306/llm_hub?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf8&useServerPrepStmts=false&rewriteBatchedStatements=true
    username: root
    password: EasyLink1!
  data:
    redis:
      host: 123.60.107.45 # Redis?????
      port: 6379
      password: 'easylink123321'
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 0
          time-between-eviction-runs: 10s
      timeout: 5000
      database: 7
mybatis-plus:
  configuration:
    log-impl:  org.apache.ibatis.logging.nologging.NoLoggingImpl
    logPrefix: [ "SQL: ", "SQL_TIME: " ]


logging:
  level:
    org.sycamore.llmhub.core.client.ReactorNettyClient: DEBUG


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-do  cs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.sycamore.nextblog
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn